server {
    listen $PORT;
    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass https://diploma-backend-af24de726588.herokuapp.com/api/;
        proxy_set_header Host diploma-backend-af24de726588.herokuapp.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_ssl_server_name on;
    }

    location /ws/ {
        proxy_pass https://diploma-backend-af24de726588.herokuapp.com/ws/;
        proxy_set_header Host diploma-backend-af24de726588.herokuapp.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_ssl_server_name on;
        proxy_http_version 1.1;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}